import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faGithubAlt,
  faFacebook,
  faYoutube,
  faLinkedin,
  faGoogle,
  faGithub,
  faWhatsapp,
  faViber,
} from '@fortawesome/free-brands-svg-icons'
import {
  faCampground,
  faHouseChimney,
  faSuitcase,
  faFeather,
  faCircleQuestion,
  faFillDrip,
  faRightToBracket,
  faRightFromBracket,
  faEye,
  faEyeSlash,
  faPeoplePulling,
  faSpinner,
  faFireFlameCurved,
  faCircleInfo,
  faTriangleExclamation,
  faCircleCheck as faCircleCheckSolid,
  faCircleXmark as faCircleXMarkSolid,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

import { faCircleXmark, faCircleCheck } from '@fortawesome/free-regular-svg-icons'

library.add(
  faGithubAlt,
  faCampground,
  faFacebook,
  faHouseChimney,
  faSuitcase,
  faFeather,
  faCircleQuestion,
  faFillDrip,
  faYoutube,
  faLinkedin,
  faGoogle,
  faGithub,
  faWhatsapp,
  faViber,
  faRightToBracket,
  faRightFromBracket,
  faEyeSlash,
  faEye,
  faPeoplePulling,
  faSpinner,
  faCircleCheck,
  faCircleXmark,
  faFireFlameCurved,
  faCircleInfo,
  faTriangleExclamation,
  faCircleXMarkSolid,
  faCircleCheckSolid,
  faXmark
)
